// ============================================================================
// This is auto-generated by gf cli tool only once. Fill this file as you wish.
// ============================================================================

package dao

import (
	"gf-practice/app/admin/dao/internal"
)

// actionDao is the manager for logic model data accessing
// and custom defined data operations functions management. You can define
// methods on it to extend its functionality as you wish.
type actionDao struct {
	internal.ActionDao
}

var (
	// Action is globally public accessible object for table cd_action operations.
	Action = actionDao{
		internal.Action,
	}
)

// Fill with you ideas below.
