// ============================================================================
// This is auto-generated by gf cli tool only once. Fill this file as you wish.
// ============================================================================

package dao

import (
	"gf-practice/app/admin/dao/internal"
)

// adminTokenDao is the manager for logic model data accessing
// and custom defined data operations functions management. You can define
// methods on it to extend its functionality as you wish.
type adminTokenDao struct {
	internal.AdminTokenDao
}

var (
	// AdminToken is globally public accessible object for table cd_admin_token operations.
	AdminToken = adminTokenDao{
		internal.AdminToken,
	}
)

// Fill with you ideas below.
