// ============================================================================
// This is auto-generated by gf cli tool only once. Fill this file as you wish.
// ============================================================================

package dao

import (
	"gf-practice/app/admin/dao/internal"
)

// applicationDao is the manager for logic model data accessing
// and custom defined data operations functions management. You can define
// methods on it to extend its functionality as you wish.
type applicationDao struct {
	internal.ApplicationDao
}

var (
	// Application is globally public accessible object for table cd_application operations.
	Application = applicationDao{
		internal.Application,
	}
)

// Fill with you ideas below.
