// ============================================================================
// This is auto-generated by gf cli tool only once. Fill this file as you wish.
// ============================================================================

package dao

import (
	"gf-practice/app/admin/dao/internal"
)

// baseConfigDao is the manager for logic model data accessing
// and custom defined data operations functions management. You can define
// methods on it to extend its functionality as you wish.
type baseConfigDao struct {
	internal.BaseConfigDao
}

var (
	// BaseConfig is globally public accessible object for table cd_base_config operations.
	BaseConfig = baseConfigDao{
		internal.BaseConfig,
	}
)

// Fill with you ideas below.
