// ============================================================================
// This is auto-generated by gf cli tool only once. Fill this file as you wish.
// ============================================================================

package dao

import (
	"gf-practice/app/admin/dao/internal"
)

// secrectDao is the manager for logic model data accessing
// and custom defined data operations functions management. You can define
// methods on it to extend its functionality as you wish.
type secrectDao struct {
	internal.SecrectDao
}

var (
	// Secrect is globally public accessible object for table cd_secrect operations.
	Secrect = secrectDao{
		internal.Secrect,
	}
)

// Fill with you ideas below.
