// ============================================================================
// This is auto-generated by gf cli tool only once. Fill this file as you wish.
// ============================================================================

package dao

import (
	"gf-practice/app/admin/dao/internal"
)

// uploadConfigDao is the manager for logic model data accessing
// and custom defined data operations functions management. You can define
// methods on it to extend its functionality as you wish.
type uploadConfigDao struct {
	internal.UploadConfigDao
}

var (
	// UploadConfig is globally public accessible object for table cd_upload_config operations.
	UploadConfig = uploadConfigDao{
		internal.UploadConfig,
	}
)

// Fill with you ideas below.
