// ==========================================================================
// This is auto-generated by gf cli tool. DO NOT EDIT THIS FILE MANUALLY.
// ==========================================================================

package internal

// User is the golang structure for table prac_user.
type User struct {
	UserId    int    `orm:"userId,primary" json:"userId"`    // 用户表主键
	UserName  string `orm:"userName"       json:"userName"`  // 用户名
	Password  string `orm:"password"       json:"password"`  // 用户密码
	AvatarUrl string `orm:"avatarUrl"      json:"avatarUrl"` // 头像
	NickName  string `orm:"nickName"       json:"nickName"`  // 用户昵称
	Gender    int    `orm:"gender"         json:"gender"`    // 用户性别 1|男 2|女
}
