// ==========================================================================
// This is auto-generated by gf cli tool. Fill this file as you wish.
// ==========================================================================

package model

import (
	"gf-practice/app/admin/model/internal"
)

// Action is the golang structure for table cd_action.
type Action internal.Action

// Fill with you ideas below.
