// ==========================================================================
// This is auto-generated by gf cli tool. Fill this file as you wish.
// ==========================================================================

package model

import (
	"gf-practice/app/admin/model/internal"
)

// AdminUser is the golang structure for table cd_admin_user.
type AdminUser internal.AdminUser

// Fill with you ideas below.
