// ==========================================================================
// This is auto-generated by gf cli tool. Fill this file as you wish.
// ==========================================================================

package model

import (
	"gf-practice/app/admin/model/internal"
)

// AdminToken is the golang structure for table cd_admin_token.
type AdminToken internal.AdminToken

// Fill with you ideas below.
