// ==========================================================================
// This is auto-generated by gf cli tool. Fill this file as you wish.
// ==========================================================================

package model

import (
	"gf-practice/app/admin/model/internal"
)

// AdminUser is the golang structure for table cd_admin_user.
type AdminUser internal.AdminUser

// Fill with you ideas below.

// 登录接口请求参数定义
type AdminUserApiLoginReq struct {
	User string `v:"required|length:3,16#账号不能为空|账号长度应当在:min到:max之间"`
	Pwd  string `v:"required|length:6,16#请输入确认密码|密码长度应当在:min到:max之间"`
}
