// ==========================================================================
// This is auto-generated by gf cli tool. Fill this file as you wish.
// ==========================================================================

package model

import (
	"gf-practice/app/admin/model/internal"
)

// Application is the golang structure for table cd_application.
type Application internal.Application

// Fill with you ideas below.
