// ==========================================================================
// This is auto-generated by gf cli tool. Fill this file as you wish.
// ==========================================================================

package model

import (
	"gf-practice/app/admin/model/internal"
)

// BaseConfig is the golang structure for table cd_base_config.
type BaseConfig internal.BaseConfig

// Fill with you ideas below.
