// ==========================================================================
// This is auto-generated by gf cli tool. Fill this file as you wish.
// ==========================================================================

package model

import (
	"gf-practice/app/admin/model/internal"
)

// Field is the golang structure for table cd_field.
type Field internal.Field

// Fill with you ideas below.
