// ==========================================================================
// This is auto-generated by gf cli tool. Fill this file as you wish.
// ==========================================================================

package model

import (
	"gf-practice/app/admin/model/internal"
)

// File is the golang structure for table cd_file.
type File internal.File

// Fill with you ideas below.
