// ==========================================================================
// This is auto-generated by gf cli tool. Fill this file as you wish.
// ==========================================================================

package model

import (
	"gf-practice/app/admin/model/internal"
)

// Log is the golang structure for table cd_log.
type Log internal.Log

// Fill with you ideas below.
