// ==========================================================================
// This is auto-generated by gf cli tool. Fill this file as you wish.
// ==========================================================================

package model

import (
	"gf-practice/app/admin/model/internal"
)

// Menu is the golang structure for table cd_menu.
type Menu internal.Menu

// Fill with you ideas below.
