// ==========================================================================
// This is auto-generated by gf cli tool. Fill this file as you wish.
// ==========================================================================

package model

import (
	"gf-practice/app/admin/model/internal"
)

// Role is the golang structure for table cd_role.
type Role internal.Role

// Fill with you ideas below.
