// ==========================================================================
// This is auto-generated by gf cli tool. Fill this file as you wish.
// ==========================================================================

package model

import (
	"gf-practice/app/admin/model/internal"
)

// Secrect is the golang structure for table cd_secrect.
type Secrect internal.Secrect

// Fill with you ideas below.
