// ==========================================================================
// This is auto-generated by gf cli tool. Fill this file as you wish.
// ==========================================================================

package model

import (
	"gf-practice/app/admin/model/internal"
)

// UploadConfig is the golang structure for table cd_upload_config.
type UploadConfig internal.UploadConfig

// Fill with you ideas below.
