// ==========================================================================
// This is auto-generated by gf cli tool. Fill this file as you wish.
// ==========================================================================

package model

import (
	"gf-practice/app/api/model/internal"
)

// Todo is the golang structure for table prac_todo.
type Todo internal.Todo

// Fill with you ideas below.
