# HTTP Server
[status]
    admin = true
    api = true

[server]
	Address     = ":8199"
	ServerRoot  = ""
	ServerAgent = "yj-app"
	LogPath     = "/tmp/log/yj-app/server"
  PassSecret  = "gfsadmin"

[api]
	Address     = ":8089"
	ServerRoot  = ""
	ServerAgent = "yj-app"
	LogPath     = "/tmp/log/yj-app/api"
	#jwt配置
	[api.jwt]
	    #过期时间
        timeout = 3600
        #token分割符
        refresh = 1800
        #安全密钥
        encryptKey = "yjgoyjgoyjgoyjgo"

# Logger.
[logger]
    Path        = "/tmp/log/yj-app"
    Level       = "all"
    Stdout      = true

# Template.
[viewer]
    Path        = "template"
    DefaultFile = "index.html"
    Delimiters  =  ["{{", "}}"]

# Database.
[database]
    [[database.default]]
        link  = "mysql:goframe:paJayS7FA734Eexp@tcp(129.204.48.98:3306)/goframe"
        debug = true
    [[database.admin]]
        link  = "mysql:gfadmin:33AjMzd3Jzt26SJP@tcp(129.204.48.98:3306)/gfadmin"
        debug = true
        prefix = "cd_"
    # Database logger.
    [database.logger]
        Path   = "/tmp/log/yj-app/sql"
        Level  = "all"
        Stdout = true

# Gen
[gen]
    author        = "shoujing"
    moduleName    = "module"
    packageName   = "gf-practice"
    autoRemovePre = true
    tablePrefix   = "t_,sys_"

[compiler]
    name     = "yj-app"
    version  = "1.0.0"
    arch     = "i386,amd64"
    system   = "linux,darwin"
    output   = ""
    path     = "./bin"
    extra    = "-ldflags \"-s -w\""
    # 自定义编译时内置变量
    [compiler.VarMap]
        author = "yjgo"
        email  = "yjgo@163.org"

[gfcli]
    [[gfcli.gen.dao]]
        link   = "mysql:goframe:paJayS7FA734Eexp@tcp(129.204.48.98:3306)/goframe"
        group  = ""
        prefix = ""
        tables = ""
    [[gfcli.gen.dao]]
        link   = "mysql:gfadmin:33AjMzd3Jzt26SJP@tcp(129.204.48.98:3306)/gfadmin"
        group  = "admin"
        prefix = "cd_"
        tables = ""