### signup
post http://localhost:8089/user/signup
Content-Type: application/json

{
  "user_name": "shoujing",
  "password": "a123456",
  "password2": "a123456",
  "nick_name": "hellogf"
}

### signin
post http://localhost:8089/user/signin
Content-Type: application/json

{
  "user_name": "shoujing",
  "password": "a1234567"
}