### signup
post http://localhost:8089/user/signup
Content-Type: application/json

{
  "user_name": "shoujing",
  "password": "a123456",
  "password2": "a123456",
  "nick_name": "hellogf"
}

### signin
post http://localhost:8089/user/signin
Content-Type: application/json

{
  "user_name": "shoujing",
  "password": "a123456"
}


### admin/login
post http://localhost:8199/sys/login
Content-Type: application/json

{
  "user": "sanshang",
  "pwd": "admin123"
}

### admin/getUserInfo
post http://localhost:8199/sys/getUserInfo
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJTdGFuZGFyZENsYWltcyI6eyJleHAiOjE2MjM2NDc2OTYsImp0aSI6IjI5IiwiaWF0IjoxNjIzNjQ0MDk2fSwiUmVmcmVzaFRpbWUiOjE2MjM2NDU4OTZ9.nAMzz-ojhOvd2abjVAPVkxGPWZjtQ2Npn1PDpOfqENM

{
  "user": "gfsadmin",
  "pwd": "admin123"
}