// ==========================================================================
// This is auto-generated by gf cli tool. DO NOT EDIT THIS FILE MANUALLY.
// ==========================================================================

package internal

// Action is the golang structure for table cd_action.
type Action struct {
	Id                 int    `orm:"id,primary"           json:"id"`                 //
	MenuId             int    `orm:"menu_id"              json:"menuId"`             // 模块ID
	Name               string `orm:"name"                 json:"name"`               // 动作名称
	ActionName         string `orm:"action_name"          json:"actionName"`         // 动作名称
	Type               int    `orm:"type"                 json:"type"`               //
	Icon               string `orm:"icon"                 json:"icon"`               // icon图标
	Pagesize           string `orm:"pagesize"             json:"pagesize"`           // 每页显示数据条数
	GroupButtonStatus  int    `orm:"group_button_status"  json:"groupButtonStatus"`  // 按钮组显示状态
	ListButtonStatus   int    `orm:"list_button_status"   json:"listButtonStatus"`   // 按钮是否显示列表
	ButtonColor        string `orm:"button_color"         json:"buttonColor"`        //
	Fields             string `orm:"fields"               json:"fields"`             // 操作的字段
	Sortid             int    `orm:"sortid"               json:"sortid"`             // 排序
	Orderby            string `orm:"orderby"              json:"orderby"`            // 配置排序
	TreeConfig         string `orm:"tree_config"          json:"treeConfig"`         //
	Jump               string `orm:"jump"                 json:"jump"`               // 按钮跳转地址
	ServerCreateStatus int    `orm:"server_create_status" json:"serverCreateStatus"` //
	VueCreateStatus    int    `orm:"vue_create_status"    json:"vueCreateStatus"`    // 视图生成
	CacheTime          int    `orm:"cache_time"           json:"cacheTime"`          // 缓存时间
	ApiAuth            int    `orm:"api_auth"             json:"apiAuth"`            // 接口是否鉴权
	ImgAuth            int    `orm:"img_auth"             json:"imgAuth"`            // 图片验证码鉴权
	SmsAuth            int    `orm:"sms_auth"             json:"smsAuth"`            // 短信验证
	ListFilter         string `orm:"list_filter"          json:"listFilter"`         // 过滤
	TabConfig          string `orm:"tab_config"           json:"tabConfig"`          //
	Sql                string `orm:"sql"                  json:"sql"`                //
	DialogSize         string `orm:"dialog_size"          json:"dialogSize"`         //
	StatusVal          string `orm:"status_val"           json:"statusVal"`          //
	Validate           string `orm:"validate"             json:"validate"`           //
	SelectType         int    `orm:"select_type"          json:"selectType"`         // 选中方式 1多选 2单选
	TableHeight        string `orm:"table_height"         json:"tableHeight"`        // 表格高度
	LeftTreeSql        string `orm:"left_tree_sql"        json:"leftTreeSql"`        // 侧栏生成的sql
	WithJoin           string `orm:"with_join"            json:"withJoin"`           // 关联模型
	OtherConfig        string `orm:"other_config"         json:"otherConfig"`        // 登录字段配置
}
