// ==========================================================================
// This is auto-generated by gf cli tool. DO NOT EDIT THIS FILE MANUALLY.
// ==========================================================================

package internal

// AdminToken is the golang structure for table cd_admin_token.
type AdminToken struct {
	Id         int    `orm:"id,primary"  json:"id"`         //
	Username   string `orm:"username"    json:"username"`   // 用户名
	Token      string `orm:"token"       json:"token"`      //
	ExpireTime int    `orm:"expire_time" json:"expireTime"` //
	Status     int    `orm:"status"      json:"status"`     // 状态
	DevStatus  int    `orm:"dev_status"  json:"devStatus"`  // 1正常 0下线
}
