// ==========================================================================
// This is auto-generated by gf cli tool. DO NOT EDIT THIS FILE MANUALLY.
// ==========================================================================

package internal

// Application is the golang structure for table cd_application.
type Application struct {
	AppId           int    `orm:"app_id,primary"   json:"appId"`           //
	ApplicationName string `orm:"application_name" json:"applicationName"` //
	AppDir          string `orm:"app_dir"          json:"appDir"`          //
	Status          int    `orm:"status"           json:"status"`          //
	AppType         int    `orm:"app_type"         json:"appType"`         //
	LoginTable      string `orm:"login_table"      json:"loginTable"`      //
	LoginFields     string `orm:"login_fields"     json:"loginFields"`     //
	Domain          string `orm:"domain"           json:"domain"`          //
	Pk              string `orm:"pk"               json:"pk"`              // 登录表主键
}
