// ==========================================================================
// This is auto-generated by gf cli tool. DO NOT EDIT THIS FILE MANUALLY.
// ==========================================================================

package internal

// BaseConfig is the golang structure for table cd_base_config.
type BaseConfig struct {
	Id   int    `orm:"id,primary" json:"id"`   // 编号
	Name string `orm:"name"       json:"name"` //
	Data string `orm:"data"       json:"data"` //
}
