// ==========================================================================
// This is auto-generated by gf cli tool. DO NOT EDIT THIS FILE MANUALLY.
// ==========================================================================

package internal

// Log is the golang structure for table cd_log.
type Log struct {
	Id              int    `orm:"id,primary"       json:"id"`              //
	ApplicationName string `orm:"application_name" json:"applicationName"` // 应用名称
	Username        string `orm:"username"         json:"username"`        // 操作用户
	Url             string `orm:"url"              json:"url"`             // 请求url
	Ip              string `orm:"ip"               json:"ip"`              // ip
	Useragent       string `orm:"useragent"        json:"useragent"`       // useragent
	Content         string `orm:"content"          json:"content"`         // 请求内容
	Errmsg          string `orm:"errmsg"           json:"errmsg"`          // 异常信息
	CreateTime      int    `orm:"create_time"      json:"createTime"`      // 创建时间
	Type            int    `orm:"type"             json:"type"`            // 类型
	Times           int    `orm:"times"            json:"times"`           // 日期
}
