// ==========================================================================
// This is auto-generated by gf cli tool. DO NOT EDIT THIS FILE MANUALLY.
// ==========================================================================

package internal

// Menu is the golang structure for table cd_menu.
type Menu struct {
	MenuId         int    `orm:"menu_id,primary"  json:"menuId"`         //
	Pid            int    `orm:"pid"              json:"pid"`            // 父级id
	ControllerName string `orm:"controller_name"  json:"controllerName"` // 模块名称
	Title          string `orm:"title"            json:"title"`          // 模块标题
	Pk             string `orm:"pk"               json:"pk"`             // 主键名
	TableName      string `orm:"table_name"       json:"tableName"`      // 模块数据库表
	CreateCode     int    `orm:"create_code"      json:"createCode"`     // 是否允许生成模块
	Status         int    `orm:"status"           json:"status"`         // 0隐藏 1显示
	Sortid         int    `orm:"sortid"           json:"sortid"`         // 排序号
	CreateTable    int    `orm:"create_table"     json:"createTable"`    // 是否生成数据库表
	ComponentPath  string `orm:"component_path"   json:"componentPath"`  // 组件路径
	Icon           string `orm:"icon"             json:"icon"`           // icon字体图标
	TabConfig      string `orm:"tab_config"       json:"tabConfig"`      // tab选项卡菜单配置
	AppId          int    `orm:"app_id"           json:"appId"`          // 所属模块
	IsPost         int    `orm:"is_post"          json:"isPost"`         // 是否允许投稿
	UploadConfigId int    `orm:"upload_config_id" json:"uploadConfigId"` // 上传配置id
	Connect        string `orm:"connect"          json:"connect"`        // 数据库连接
	PageType       int    `orm:"page_type"        json:"pageType"`       // 页面类型
	HomeShow       int    `orm:"home_show"        json:"homeShow"`       // 首页快捷导航显示状态
	MenuPic        string `orm:"menu_pic"         json:"menuPic"`        // 快捷导航的图片
}
