// ==========================================================================
// This is auto-generated by gf cli tool. DO NOT EDIT THIS FILE MANUALLY.
// ==========================================================================

package internal

// Role is the golang structure for table cd_role.
type Role struct {
	RoleId      int    `orm:"role_id,primary" json:"roleId"`      // 编号
	Name        string `orm:"name"            json:"name"`        // 分组名称
	Status      int    `orm:"status"          json:"status"`      // 状态
	Pid         int    `orm:"pid"             json:"pid"`         // 所属父类
	Description string `orm:"description"     json:"description"` // 描述
	Access      string `orm:"access"          json:"access"`      // 权限节点
}
