// ==========================================================================
// This is auto-generated by gf cli tool. DO NOT EDIT THIS FILE MANUALLY.
// ==========================================================================

package internal

// UploadConfig is the golang structure for table cd_upload_config.
type UploadConfig struct {
	Id            int    `orm:"id,primary"     json:"id"`            //
	Title         string `orm:"title"          json:"title"`         // 配置名称
	UploadReplace int    `orm:"upload_replace" json:"uploadReplace"` // 覆盖同名文件
	ThumbStatus   int    `orm:"thumb_status"   json:"thumbStatus"`   // 缩图开关
	ThumbWidth    string `orm:"thumb_width"    json:"thumbWidth"`    // 缩放宽度
	ThumbHeight   string `orm:"thumb_height"   json:"thumbHeight"`   // 缩放高度
	ThumbType     int    `orm:"thumb_type"     json:"thumbType"`     // 缩图方式
}
